AWSTemplateFormatVersion: "2010-09-09"
Description: >
  CloudDoctor 고객사용 Audit Role
  - 권한정책: 읽기 전용/점검용
  - 신뢰정책: SaaS 계정에서 sts:AssumeRole 허용

Resources:
  CloudDoctorAuditRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CloudDoctorAuditRole
      Description: Role for CloudDoctor SaaS to perform audit in customer account
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: "arn:aws:iam::346448660196:user/clouddoctortest"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: CloudDoctorAuditPermissions
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - iam:GetAccountSummary
                  - iam:ListUsers
                  - iam:GetUser
                  - iam:ListUserPolicies
                  - iam:GetUserPolicy
                  - iam:ListAccessKeys
                  - iam:GetAccessKeyLastUsed
                  - iam:ListRoles
                  - iam:GetRole
                  - iam:ListRolePolicies
                  - iam:GetRolePolicy
                  - iam:ListAttachedUserPolicies
                  - iam:ListAttachedRolePolicies
                  - iam:GetPolicy
                  - iam:GetPolicyVersion
                  - iam:ListInstanceProfiles
                  - iam:ListInstanceProfilesForRole

                  - ec2:Describe*
                  - s3:ListAllMyBuckets
                  - s3:GetBucketAcl
                  - s3:GetBucketPolicy
                  - s3:GetBucketPublicAccessBlock
                  - s3:GetBucketPolicyStatus
                  - s3:GetBucketLocation
                  - s3:GetBucketLogging
                  - s3:GetReplicationConfiguration
                  - s3:GetEncryptionConfiguration

                  - kms:ListKeys
                  - kms:DescribeKey
                  - kms:GetKeyPolicy

                  - cloudtrail:DescribeTrails
                  - cloudtrail:GetEventSelectors
                  - cloudtrail:GetTrailStatus

                  - cloudformation:DescribeStacks
                  - rds:Describe*
                  - sns:ListTopics
                  - sns:GetTopicAttributes

                  - cognito-idp:ListUserPools
                  - cognito-idp:DescribeUserPool
                  - cognito-idp:ListUserPoolClients
                  - cognito-idp:DescribeUserPoolClient

                  - guardduty:ListDetectors
                  - guardduty:GetDetector
                  - guardduty:ListFindings
                  - guardduty:GetFindings

                  - es:ListDomainNames
                  - es:DescribeElasticsearchDomains
                  - es:DescribeDomain

                  - organizations:ListPolicies
                  - organizations:ListAccounts
                  - organizations:ListRoots
                  - organizations:ListOrganizationalUnitsForParent
                  - organizations:ListChildren

                  - sqs:ListQueues
                  - sqs:GetQueueAttributes

                  - ses:ListIdentities
                  - ses:GetIdentityPolicy
                  - ses:ListIdentityPolicies

                  - ecr:DescribeRepositories
                  - ecr:ListImages
                  - ecr:DescribeImages

                  - redshift:DescribeClusters
                  - redshift:DescribeClusterSubnetGroups
                  - redshift:DescribeClusterSecurityGroups

                  - ssm:ListDocuments
                  - ssm:GetDocument
                  - ssm:ListCommandInvocations
                  - ssm:ListCommands

                  - logs:DescribeLogGroups
                  - logs:DescribeLogStreams
                  - logs:GetLogEvents

                  - lambda:ListFunctions
                  - lambda:GetFunctionConfiguration
                Resource: "*"
